name: lyrica
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.0.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
  assets:
    - assets/audio/intro_music.m4a
    - assets/audio/A/
    - assets/audio/B/
    - assets/audio/C/
    - assets/audio/D/
    - assets/audio/E/
    - assets/audio/F/
    - assets/audio/G/
    - assets/images/wood.png
    - assets/images/
    - assets/audio/Data_Structures_audio/
  